version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: always
    volumes: 
      - "./src:/var/www/html"
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - "./src2:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
